Added native core dump handling in cf-support for solaris
Ticket: ENT-9786
Changelog: title

diff --git a/misc/cf-support b/misc/cf-support
--- a/misc/cf-support
+++ b/misc/cf-support
@@ -167,15 +167,21 @@ else
     # core: ELF 64-bit LSB core file, x86-64, version 1 (SYSV), SVR4-style, from '/var/cfengine/bin/cf-key', real uid: 0, effective uid: 0, realgid: 0, effective gid: 0, execfn: '/var/cfengine/bin/cf-key', platform: 'x86_64'
     cf_core_files=`find "$response" -name 'core*' -type f -exec file {} \; 2>/dev/null | grep "core file" | grep "cf-" | cut -d' ' -f1 | sed 's/:$//'`
     if [ -n "$cf_core_files" ]; then
-      if ! command -v gdb >/dev/null; then
-        echo "Please install gdb. This is required in order to analyze core dumps."
-        exit 1
+      if [ "$OS" != "solaris" ]; then
+        if ! command -v gdb >/dev/null; then
+          echo "Please install gdb. This is required in order to analyze core dumps."
+          exit 1
+        fi
       fi
       for core_file in $cf_core_files; do
         file "$core_file" >> "$_core_log"
-        execfn=`file "$core_file" | sed 's/,/\n/g' | grep execfn | cut -d: -f2 | sed "s/[' ]//g"`
-        exe="`realpath "$execfn"`"
-        gdb "$exe" --core="$core_file" -batch -ex "thread apply all bt full" >> "$_core_log" 2>&1
+        if [ "$OS" = "solaris" ]; then
+          pstack "$core_file" >> "$_core_log" 2>&1
+        else
+          execfn=`file "$core_file" | sed 's/,/\n/g' | grep execfn | cut -d: -f2 | sed "s/[' ]//g"`
+          exe="`realpath "$execfn"`"
+          gdb "$exe" --core="$core_file" -batch -ex "thread apply all bt full" >> "$_core_log" 2>&1
+        fi
       done
     fi
   fi
