Add a way to run selected subdirectory of unit tests

diff --git a/tests/testall b/tests/testall
--- a/tests/testall
+++ b/tests/testall
@@ -197,10 +197,17 @@ fi
 
 if [ $# -gt 0 ]; then
   for test in "$@"; do
-    if expr "$test" : '^[/.]' >/dev/null; then
+    if ! expr "$test" : '^[/.]' >/dev/null; then
+      test="./$test"
+    fi
+
+    if [ -f $test ]; then
       TESTS="$TESTS $test"
+    elif [ -d $test ]; then
+      ADDTESTS=$(find $test -name '[0-9][0-9][0-9]*.cf' | sort)
+      TESTS="$TESTS $ADDTESTS"
     else
-      TESTS="$TESTS ./$test"
+      echo "Unable to open test file/directory: $test"
     fi
   done
 else
