Replace date +%s in testall with more widely compatible code (Mantis #1254)
In order to calculate the total run time of acceptance tests, the
testall script needs the UNIX seconds - a time() call - of the start
and end times of the test runs. It currently uses the command
"date +%s" to get these times.

Many older OS platforms - such as HP-UX 11.11, Solaris 8 and 9, and
others - do not support the "%s" format for the date command.

This patch creates a unix_seconds() subroutine which uses the modern
"date +%s" command if available, falls back to a Perl "print time()"
call, and failing that it falls back to pulling the octal date out of
a pax-created cpio header for an empty temporary file and converting
it to decimal using "bc."

This code will work on every POSIX-compliant platform (since the
pax/cpio/bc approach is strictly POSIX) as well as any platorm that
has a copy of Perl in the path.

Conflicts:
	tests/acceptance/testall

diff --git a/tests/acceptance/testall b/tests/acceptance/testall
--- a/tests/acceptance/testall
+++ b/tests/acceptance/testall
@@ -38,6 +38,38 @@ SKIPPED_TESTS=0
 
 [ x"$GREP" == x ] && GREP=`which grep`
 
+#
+# Many older platforms don't support date +%s, so check for compatibility
+# and find Perl for the unix_seconds() routine below. (Mantis #1254)
+#
+HAVE_DATE_PCT_S=
+if [ x`date +%s 2>/dev/null` != x'%s'  -a  $? -eq 0 ] ; then
+  HAVE_DATE_PCT_S=1
+fi
+PERL=`which perl 2>/dev/null`
+
+#
+# Obtain UNIX time(), using date +%s, Perl, or POSIX-compatible approach.
+#
+unix_seconds() {
+  if [ "$HAVE_DATE_PCT_S" ]; then
+    date +%s
+    return 0
+  fi
+
+  if [ "$PERL" ]; then
+    $PERL -e 'print time() . "\n"' 2>/dev/null
+    if [ $? -eq 0 ] ; then
+      return 0
+    fi
+  fi
+
+  # Last resort if Perl fails - the extended cpio interchange format has
+  # the file modification timestamp in columns 48-59, in octal.
+  : > $BASE_WORKDIR/x
+  echo "ibase=8;$(pax -wx cpio $BASE_WORKDIR/$$.seconds | cut -c 48-59)" | bc 2>/dev/null
+  rm $BASE_WORKDIR/x
+}
 
 curdir() {
   case $(dirname "$0") in
@@ -252,7 +284,7 @@ else
 fi
 
 TESTS_COUNT=$(echo $TESTS | wc -w)
-START_TIME=$(date +%s)
+START_TIME=$(unix_seconds)
 
 ( echo ======================================================================
   echo Testsuite started at $(date "+%F %T")
@@ -269,7 +301,7 @@ for test in $TESTS; do
   fi
 done
 
-END_TIME=$(date +%s)
+END_TIME=$(unix_seconds)
 
 ( echo
   echo ======================================================================
